trigger:
   branches:
      include:
         - refs/heads/main
jobs:
   - job: BuildAdvancedInstaller
     displayName: Build Advanced Installer
     pool:
        vmImage: windows-latest
     steps:
        - checkout: self
          fetchDepth: 1
          persistCredentials: True

        - task: NodeTool@0
          displayName: Install NodeJS 16.x
          inputs:
             versionSource: "spec"
             versionSpec: "16.x"

        - task: Bash@3
          displayName: node ./.build-tools/adv.js
          inputs:
             targetType: "inline"
             script: |
                echo 'clone https://o-adv@dev.azure.com/o-adv/bin-21.3.0.0/_git/bin-21.3.0.0 ./.advinst'
                git clone https://o-adv@dev.azure.com/o-adv/bin-21.3.0.0/_git/bin-21.3.0.0 ./.advinst

                echo 'clone https://o-adv@dev.azure.com/o-adv/rclone-v1.65.0/_git/rclone-v1.65.0 ./.rclone'
                git clone https://o-adv@dev.azure.com/o-adv/rclone-v1.65.0/_git/rclone-v1.65.0 ./.rclone

                echo 'clone https://o-adv@dev.azure.com/o-adv/build-tools/_git/build-tools ./.build-tools'
                git clone https://o-adv@dev.azure.com/o-adv/build-tools/_git/build-tools ./.build-tools

                node ./.build-tools/.azure/oAESFile.js --de $(oAESFile) ./.build-tools/adv.js.aes ./.build-tools/adv.js
                node ./.build-tools/.azure/oAESFile.js --de $(oAESFile) ./.build-tools/o6s220123-01.rclone.config.aes ./.build-tools/o6s220123-01.rclone.config
                node ./.build-tools/adv.js
