trigger:
   branches:
      include:
         - refs/heads/main
jobs:
   - job: PushRemotes
     displayName: Push code to multi remotes
     pool:
        vmImage: ubuntu-latest
     steps:
        - task: NodeTool@0
          displayName: Install NodeJS 16.x
          inputs:
             versionSource: "spec"
             versionSpec: "16.x"

        - task: Bash@3
          env:
             SYTEM_ACCESS_TOKEN: $(System.AccessToken)
             BUILD_REPOSITORY_URI: $(BUILD_REPOSITORY_URI)
          displayName: Push code to multi remotes
          inputs:
             targetType: "inline"
             script: |
                echo 'clone $(Build.Repository.Uri)'
                git clone $(Build.Repository.Uri) ./cloneRepo
                echo 'Change directory working: ./cloneRepo'
                cd ./cloneRepo
                git config user.email "deploy-repo@gmail.com"
                git config user.name "deploy-repo"
                git checkout -b main
                git add .
                git commit -m "Push code to multi remotes"
                node ./.azure/oAESFile.js --de "$(oAESFile)" ./.azure/push.sh.aes ./.azure/push.sh
                echo 'Push code to multi remotes'
                chmod u=rwx ./.azure/push.sh
                ./.azure/push.sh
